### ISSUE TITLE
Out of memory exception on RTX 3060

### ISSUE THREAD

**Issue by samuelmorais** [JiehongLin/SAM-6D#13]
Hi,
Thanks for sharing this code.
I am having a problem when executing the "demo.sh" script:

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 5.80 GiB total capacity; 4.81 GiB already allocated; 724.81 MiB free; 4.92 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
set CUDA_VISIBLE_DEVICES as 0
```

I've tried to change the points_per_batch value in the automatic_mask_generator.py file, but it didn't solve the problem.

Is it because this algorithm requires more than 8 GB memory on the GPU?

I am using RTX 3060 with 8GB RAM.

**Comment by samuelmorais** [comment]
Just to complement, here is my nvidia-smi output:

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.146.02             Driver Version: 535.146.02   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060 ...    Off | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P0              N/A / 115W |      8MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1270      G   /usr/lib/xorg/Xorg                            4MiB |
+---------------------------------------------------------------------------------------+

**Comment by samuelmorais** [comment]
And here is my cuda version:
```

(sam6d) samuel@smdell:~/repos/SAM-6D/SAM-6D$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

```

**Comment by samuelmorais** [comment]
I've already solved this by changed the SAM to "cpu" instead of "cuda".
